name: "Build API Docker image and push it to Docker Hub"

on:
  push:
    branches:
      - master
    paths:
      - .github/workflows/docker-api.yml
      - QuizAPI/**

jobs:
  docker-api:
    if:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: indyteo/quiz-prod-api
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: QuizAPI
          push: true
          tags: indyteo/quiz-prod-api:latest
