name: "Build UI Docker image and push it to Docker Hub"

on:
  push:
    branches:
      - master
    paths:
      - .github/workflows/docker-ui.yml
      - QuizUI/**

jobs:
  docker-ui:
    if:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: indyteo/quiz-prod-ui
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: QuizUI
          push: true
          build-args: |
            api_url=/api
          tags: indyteo/quiz-prod-ui:latest
