name: Automated API tests using Postman CLI

on:
  push:
    branches-ignore:
      - release
    paths:
      - .github/workflows/postman.yml
      - QuizAPI/**

jobs:
  test-api:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r QuizAPI/requirements.txt
      - name: Install Postman CLI
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh
      - name: Login to Postman CLI
        run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}
      - name: Start QuizAPI in background
        run: cd QuizAPI && python app.py &
        env:
          FLASK_DEBUG: 0
          FLASK_ENV: test
          APP_SECRET: ${{ secrets.API_SECRET }}
          APP_ADMIN_PASSWORD: ${{ secrets.API_ADMIN_PASSWORD }}
      - name: Run API tests
        run: |
          postman collection run "26907000-20e739bf-ad44-4073-a813-21e2bd77b5ca" -e "26907000-3c0258c3-8de0-49be-963e-b7e9b7981061" --integration-id "138488-${{ github.run_id }}"
